-include "io.scl"

fn main() : i32 {
  i32 arr[10] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9}
  i32 target = 6

  i32 low = 0
  i32 high = 9

  while low <= high {
    i32 mid = (low + high) / 2

    if arr[mid] == target {
      printf("target found at index %d\n", mid)
      return 0
    }

    if arr[mid] < target {
      low = mid + 1
    } else {
      high = mid - 1
    }
  }

  printf("target not found\n")
  return 0
}
